/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  jiraw
 * Created: Oct 6, 2016
 */
create table ACCOUNTS
(
	ID INTEGER not null primary key,
	USERNAME VARCHAR(255) not null,
	PASSWORD VARCHAR(255) not null,
	STAFF_ID INTEGER not null
)

create table COMPANIES
(
	COMPANY_ID INTEGER not null primary key,
	COMPANY_NAME VARCHAR(255) not null,
	COMPANY_DESCRIPTION VARCHAR(255)
)

create table ORDERDETAIL
(
	ID INTEGER not null,
	ORDER_ID INTEGER not null,
	ITEM_NO INTEGER not null primary key,
	PROD_ID BIGINT not null, 
	AMOUNT INTEGER not null,
	PRICE DOUBLE not null
)

create table ORDERS
(
	ORDER_ID INTEGER not null primary key,
	STAFF_ID INTEGER not null,
	ORDERTYPEID INTEGER not null,
	DATE_ORDER DATE not null
)

create table ORDERTYPES
(
	ORDERTYPEID INTEGER not null primary key,
	ORDERTYPE VARCHAR(255) not null
)

create table PRODUCT_STATUS
(
	ID INTEGER not null primary key,
	PROD_ID BIGINT not null,
	CANCLE_STATUS BOOLEAN not null
)

create table PRODUCTS
(
	PROD_ID BIGINT not null primary key,
	PROD_NAME VARCHAR(255) not null,
	PRICE DOUBLE not null,
	AMOUNT INTEGER not null,
	WAREHOUSE_ID INTEGER not null,
	PROD_TYPE VARCHAR(255) not null,
	COMPANY_ID INTEGER not null
)

create table STAFFS
(
	STAFF_ID INTEGER not null primary key not null,
	COMPANY_ID INTEGER not null,
	FIRSTNAME VARCHAR(255) not null,
	LASNAME VARCHAR(255) not null,
	CITIZENNO NUMERIC(13) not null,
	ADDRESS VARCHAR(255) not null,
	POSITION VARCHAR(255) not null
)

create table WAREHOUSES
(
	WAREHOUSE_ID INTEGER not null primary key,
	WAREHOUSE_NAME VARCHAR(255) not null,
	LOCATION VARCHAR(255) not null
)

ALTER TABLE PRODUCTS
ADD FOREIGN KEY (COMPANY_ID)
REFERENCES COMPANIES(COMPANY_ID)

ALTER TABLE PRODUCT_STATUS
ADD FOREIGN KEY (PROD_ID)
REFERENCES PRODUCTS(PROD_ID)

ALTER TABLE PRODUCTS
ADD FOREIGN KEY (WAREHOUSE_ID)
REFERENCES WAREHOUSES(WAREHOUSE_ID)

ALTER TABLE STAFFS
ADD FOREIGN KEY (COMPANY_ID)
REFERENCES COMPANIES(COMPANY_ID)

ALTER TABLE ACCOUNTS
ADD FOREIGN KEY (STAFF_ID)
REFERENCES STAFFS(STAFF_ID)

ALTER TABLE ORDERS
ADD FOREIGN KEY (ORDERTYPEID)
REFERENCES ORDERTYPES(ORDERTYPEID)

ALTER TABLE ORDERS
ADD FOREIGN KEY (STAFF_ID)
REFERENCES STAFFS(STAFF_ID)

ALTER TABLE ORDERDETAIL
ADD FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID)

ALTER TABLE ORDERDETAIL
ADD FOREIGN KEY (PROD_ID)
REFERENCES PRODUCTS(PROD_ID)
